ALTER TABLE _backup_dim_sortiment_pris_20260507 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON _backup_dim_sortiment_pris_20260507;
CREATE POLICY backup_admin_only ON _backup_dim_sortiment_pris_20260507 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE arbetsdag_backup_20260521 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON arbetsdag_backup_20260521;
CREATE POLICY backup_admin_only ON arbetsdag_backup_20260521 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_arbetsdag_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_arbetsdag_20260509;
CREATE POLICY backup_admin_only ON backup_arbetsdag_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_detalj_gps_spar_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_detalj_gps_spar_20260509;
CREATE POLICY backup_admin_only ON backup_detalj_gps_spar_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_fakt_avbrott_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_fakt_avbrott_20260509;
CREATE POLICY backup_admin_only ON backup_fakt_avbrott_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_fakt_maskin_statistik_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_fakt_maskin_statistik_20260509;
CREATE POLICY backup_admin_only ON backup_fakt_maskin_statistik_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_fakt_produktion_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_fakt_produktion_20260509;
CREATE POLICY backup_admin_only ON backup_fakt_produktion_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_fakt_skift_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_fakt_skift_20260509;
CREATE POLICY backup_admin_only ON backup_fakt_skift_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE backup_fakt_tid_20260509 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON backup_fakt_tid_20260509;
CREATE POLICY backup_admin_only ON backup_fakt_tid_20260509 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE fakt_tid_backup_2026_05_23 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON fakt_tid_backup_2026_05_23;
CREATE POLICY backup_admin_only ON fakt_tid_backup_2026_05_23 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
ALTER TABLE vilobrott_backup_20260521 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS backup_admin_only ON vilobrott_backup_20260521;
CREATE POLICY backup_admin_only ON vilobrott_backup_20260521 FOR ALL TO authenticated USING (ar_admin()) WITH CHECK (ar_admin());
