-- skotare_objekt_manuell — manuell skotning per (objekt, maskin) + objekt-nivå.
--
-- REPO↔PROD-SYNK: tabellen och alla dess kolumner byggdes upp inkrementellt i prod
-- UTAN matchande migrationsfiler (skapades ~#415, sedan ar_omlastning/avser_objekt_id,
-- nullable maskin_id + objekt-nivå-migrering 2026-08-04, och volym_egen_skotning/
-- volym_omlastning). Ingen av dessa fanns i repot → en schema-rebuild ur migrationer
-- skulle sakna hela tabellen. Den här filen REKONSTRUERAR slutläget IDEMPOTENT
-- (IF NOT EXISTS överallt), så den är en no-op mot nuvarande prod men återskapar
-- tabellen korrekt vid en ren rebuild. Speglar prod-schemat per 2026-08-23.
--
-- Läsregeln (skotad volym) bor i lib/skotat.ts (objektSkotat/resolveSkotareVolym):
--   • maskin_id NULL  = objekt-nivå-avslut (skotad_volym_manuell) → trumfar allt.
--   • maskin_id SATT  = per-maskin: volym_egen_skotning RÄKNAS, volym_omlastning ALDRIG.

CREATE TABLE IF NOT EXISTS skotare_objekt_manuell (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  objekt_id             TEXT NOT NULL,
  -- NULL = gäller hela objektet (objekt-nivå, maskinoberoende). Satt = maskinspecifik insats.
  maskin_id             TEXT,
  datum_fran            DATE,
  datum_till            DATE,
  antal_lass            NUMERIC,
  -- Äldre helhets-volym (legacy, läs-fallback när egen/omlastning saknas).
  volym_m3              NUMERIC,
  g15_timmar            NUMERIC,
  operator_id           TEXT,
  notering              TEXT,
  -- true = maskinens insats är omlastning (andra passet). Räknas ALDRIG mot skotad total.
  ar_omlastning         BOOLEAN NOT NULL DEFAULT false,
  -- När omlastningen kom in som eget objekt: dim_objekt.objekt_id den tillskrivs.
  avser_objekt_id       TEXT,
  -- Egen skotning (m³) — RÄKNAS mot objektets skotade total. Ersätter mätt lass för maskinen.
  volym_egen_skotning   NUMERIC,
  -- Omlastning (m³) — arbete, RÄKNAS ALDRIG mot skotad total.
  volym_omlastning      NUMERIC,
  skapad_tid            TIMESTAMPTZ NOT NULL DEFAULT now(),
  uppdaterad_tid        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Kolumnerna som lades till stegvis — idempotent för tabeller som redan finns.
ALTER TABLE skotare_objekt_manuell ADD COLUMN IF NOT EXISTS ar_omlastning       BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE skotare_objekt_manuell ADD COLUMN IF NOT EXISTS avser_objekt_id     TEXT;
ALTER TABLE skotare_objekt_manuell ADD COLUMN IF NOT EXISTS volym_egen_skotning NUMERIC;
ALTER TABLE skotare_objekt_manuell ADD COLUMN IF NOT EXISTS volym_omlastning    NUMERIC;
-- maskin_id gjordes nullable 2026-08-04 (objekt-nivå-rader). Idempotent.
ALTER TABLE skotare_objekt_manuell ALTER COLUMN maskin_id DROP NOT NULL;

-- Ett objekt-nivå-/hela-objektet-insats per (objekt, maskin): partiellt unikt index
-- på hela-objektet-raderna (datum_fran IS NULL). Flera datum-avgränsade tillfällen tillåts.
CREATE UNIQUE INDEX IF NOT EXISTS skotare_objekt_manuell_helobjekt_uniq
  ON skotare_objekt_manuell (objekt_id, maskin_id)
  WHERE datum_fran IS NULL;

-- RLS enligt kodbasens mönster: FOR ALL USING (true). Filtrering sker i appen.
ALTER TABLE skotare_objekt_manuell ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'skotare_objekt_manuell'
      AND policyname = 'skotare_objekt_manuell_all'
  ) THEN
    CREATE POLICY "skotare_objekt_manuell_all" ON skotare_objekt_manuell
      FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- uppdaterad_tid hålls aktuell vid UPDATE.
CREATE OR REPLACE FUNCTION set_skotare_objekt_manuell_uppdaterad_tid()
RETURNS TRIGGER AS $$
BEGIN
  NEW.uppdaterad_tid = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_skotare_objekt_manuell_uppdaterad_tid ON skotare_objekt_manuell;
CREATE TRIGGER trg_skotare_objekt_manuell_uppdaterad_tid
  BEFORE UPDATE ON skotare_objekt_manuell
  FOR EACH ROW EXECUTE FUNCTION set_skotare_objekt_manuell_uppdaterad_tid();

COMMENT ON TABLE skotare_objekt_manuell IS
  'Manuell skotning per (objekt, maskin) + objekt-nivå (maskin_id NULL). Läsregel i lib/skotat.ts: egen skotning räknas, omlastning aldrig, objekt-nivå trumfar. Schema rekonstruerat 2026-08-23 (byggdes ad-hoc i prod utan migrationer).';

-- dim_objekt manuella skotar-kolumner (även dessa applicerades utan migration).
ALTER TABLE dim_objekt ADD COLUMN IF NOT EXISTS skotad_volym_manuell NUMERIC;
ALTER TABLE dim_objekt ADD COLUMN IF NOT EXISTS skotning_g15_manuell NUMERIC;
